# Generated by Django 4.2.30 on 2026-05-29 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProsCons',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pros_cons', serialize=False, to='companies.company', verbose_name='Company')),
                ('pros', models.TextField(blank=True, null=True, verbose_name='Key Strengths (Pros)')),
                ('cons', models.TextField(blank=True, null=True, verbose_name='Key Weaknesses/Risks (Cons)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Pros & Cons Profile',
                'verbose_name_plural': 'Pros & Cons Profiles',
                'db_table': 'pros_cons',
                'ordering': ['company'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analysis', serialize=False, to='companies.company', verbose_name='Company')),
                ('compounded_sales_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Compounded Sales Growth %')),
                ('compounded_profit_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Compounded Profit Growth %')),
                ('stock_price_cagr', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Stock Price CAGR %')),
                ('roe_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Return on Equity %')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Company Growth Analysis',
                'verbose_name_plural': 'Company Growth Analyses',
                'db_table': 'analysis',
                'ordering': ['company'],
                'indexes': [models.Index(fields=['compounded_sales_growth'], name='idx_django_analysis_sales'), models.Index(fields=['roe_percentage'], name='idx_django_analysis_roe')],
            },
        ),
        migrations.CreateModel(
            name='FinancialMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Debt to Equity Ratio')),
                ('roe', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Return on Equity')),
                ('roa', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Return on Assets')),
                ('net_profit_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Net Profit Margin')),
                ('revenue_growth', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Revenue Growth Rate')),
                ('profit_growth', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Profit Growth Rate')),
                ('cash_conversion_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cash Conversion Ratio')),
                ('free_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Free Cash Flow')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_metrics', to='companies.company')),
            ],
            options={
                'db_table': 'financial_metric',
                'ordering': ['company', '-year'],
                'indexes': [models.Index(fields=['company', 'year'], name='idx_fin_metric_company_year')],
                'unique_together': {('company', 'year')},
            },
        ),
    ]
