from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_financial_health_score'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS "financial_metric" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "year" smallint NOT NULL,
                    "debt_to_equity" numeric(10, 4) NULL,
                    "roe" numeric(10, 4) NULL,
                    "roa" numeric(10, 4) NULL,
                    "net_profit_margin" numeric(10, 4) NULL,
                    "revenue_growth" numeric(10, 4) NULL,
                    "profit_growth" numeric(10, 4) NULL,
                    "cash_conversion_ratio" numeric(10, 4) NULL,
                    "free_cash_flow" numeric(15, 2) NULL,
                    "created_at" timestamp with time zone NOT NULL,
                    "updated_at" timestamp with time zone NOT NULL,
                    "company_id" bigint NOT NULL,
                    CONSTRAINT "financial_metric_company_id_year_6bbaba35_uniq" UNIQUE ("company_id", "year"),
                    CONSTRAINT "financial_metric_company_id_ac1f6500_fk_company_company_id" FOREIGN KEY ("company_id") REFERENCES "company" ("company_id") DEFERRABLE INITIALLY DEFERRED
                );
                CREATE INDEX IF NOT EXISTS "financial_metric_company_id_ac1f6500" ON "financial_metric" ("company_id");
                CREATE INDEX IF NOT EXISTS "idx_fin_metric_company_year" ON "financial_metric" ("company_id", "year");
            """,
            reverse_sql="""
                DROP TABLE IF EXISTS "financial_metric" CASCADE;
            """,
        ),
    ]
