# Generated by Django 4.2.30 on 2026-05-29 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('balance_sheet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.SmallIntegerField(verbose_name='Fiscal Year')),
                ('equity_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Equity Capital')),
                ('reserves', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Reserves & Surplus')),
                ('borrowings', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Borrowings')),
                ('other_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Other Liabilities')),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Liabilities')),
                ('fixed_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Fixed Assets')),
                ('cwip', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Capital Work-In-Progress')),
                ('investments', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Investments')),
                ('other_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Other Assets')),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Assets')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Balance Sheet',
                'verbose_name_plural': 'Balance Sheets',
                'db_table': 'balance_sheet',
                'ordering': ['company', '-year'],
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('cash_flow_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.SmallIntegerField(verbose_name='Fiscal Year')),
                ('operating_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cash from Operations')),
                ('investing_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cash from Investing')),
                ('financing_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cash from Financing')),
                ('net_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Net Cash Flow')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Cash Flow Statement',
                'verbose_name_plural': 'Cash Flow Statements',
                'db_table': 'cash_flow',
                'ordering': ['company', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=20, unique=True, verbose_name='Ticker Symbol')),
                ('company_name', models.CharField(max_length=256, unique=True, verbose_name='Company Name')),
                ('company_logo', models.CharField(blank=True, max_length=512, null=True, verbose_name='Logo URL')),
                ('chart_link', models.CharField(blank=True, max_length=512, null=True, verbose_name='Chart Link')),
                ('about_company', models.TextField(blank=True, null=True, verbose_name='About Company')),
                ('website', models.CharField(blank=True, max_length=256, null=True, verbose_name='Website')),
                ('nse_profile', models.CharField(blank=True, max_length=512, null=True, verbose_name='NSE Profile')),
                ('bse_profile', models.CharField(blank=True, max_length=512, null=True, verbose_name='BSE Profile')),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Face Value')),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Book Value')),
                ('roce_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ROCE %')),
                ('roe_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ROE %')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'company',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='ProfitAndLoss',
            fields=[
                ('profit_and_loss_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.SmallIntegerField(verbose_name='Fiscal Year')),
                ('sales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Sales/Revenue')),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Operating Expenses')),
                ('operating_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Operating Profit (EBIT)')),
                ('opm_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='OPM %')),
                ('other_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Other Income')),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Interest Expense')),
                ('depreciation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Depreciation')),
                ('profit_before_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Profit Before Tax (PBT)')),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Effective Tax %')),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Net Profit (PAT)')),
                ('eps', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Earnings Per Share (EPS)')),
                ('dividend_payout', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Dividend Payout')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_and_losses', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Profit & Loss Statement',
                'verbose_name_plural': 'Profit & Loss Statements',
                'db_table': 'profit_and_loss',
                'ordering': ['company', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.SmallIntegerField(blank=True, null=True, verbose_name='Fiscal Year')),
                ('annual_report', models.TextField(blank=True, null=True, verbose_name='Annual Report Text/URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Supporting Document',
                'verbose_name_plural': 'Supporting Documents',
                'db_table': 'document',
                'ordering': ['company', '-year'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_name'], name='idx_django_company_name'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['website'], name='idx_django_company_website'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='companies.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='companies.company', verbose_name='Company'),
        ),
        migrations.AddIndex(
            model_name='profitandloss',
            index=models.Index(fields=['year'], name='idx_django_pl_year'),
        ),
        migrations.AddIndex(
            model_name='profitandloss',
            index=models.Index(fields=['net_profit'], name='idx_django_pl_net_profit'),
        ),
        migrations.AddIndex(
            model_name='profitandloss',
            index=models.Index(fields=['eps'], name='idx_django_pl_eps'),
        ),
        migrations.AlterUniqueTogether(
            name='profitandloss',
            unique_together={('company', 'year')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['year'], name='idx_django_doc_year'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'year'], name='idx_django_doc_company_year'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['year'], name='idx_django_cf_year'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['operating_activity'], name='idx_django_cf_ops_cash'),
        ),
        migrations.AlterUniqueTogether(
            name='cashflow',
            unique_together={('company', 'year')},
        ),
        migrations.AddIndex(
            model_name='balancesheet',
            index=models.Index(fields=['year'], name='idx_django_bs_year'),
        ),
        migrations.AddIndex(
            model_name='balancesheet',
            index=models.Index(fields=['total_assets'], name='idx_django_bs_total_assets'),
        ),
        migrations.AlterUniqueTogether(
            name='balancesheet',
            unique_together={('company', 'year')},
        ),
    ]
